import { Difficulty } from "@prisma/client";

export type SeedQuiz = {
  slug: string;
  title: string;
  description: string;
  difficulty: Difficulty;
  tags: string[];
  items: Array<{
    questionEs: string;
    questionEn: string;
    options: string[];
    answerIndex: number;
    explanationEs: string;
    explanationEn: string;
  }>;
};

export const quizSeed: SeedQuiz[] = [
  {
    slug: "frontend-basics",
    title: "Fundamentos Frontend",
    description: "Repaso rapido de conceptos clave en React y CSS.",
    difficulty: Difficulty.easy,
    tags: ["frontend", "react", "css"],
    items: [
      {
        questionEs: "Que hace el hook useMemo?",
        questionEn: "What does the useMemo hook do?",
        options: [
          "Memoriza un valor derivado para evitar calculos costosos",
          "Dispara efectos secundarios al montar",
          "Actualiza refs sincronamente",
        ],
        answerIndex: 0,
        explanationEs: "useMemo memoriza resultados en funcion de dependencias para evitar recomputar.",
        explanationEn: "useMemo caches results based on dependencies to avoid recomputation.",
      },
      {
        questionEs: "Que logra grid-template-columns: repeat(auto-fit, minmax(240px, 1fr))?",
        questionEn: "What does grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)) achieve?",
        options: [
          "Columnas fijas de 240px",
          "Columnas fluidas que se adaptan al ancho disponible",
          "Oculta columnas cuando no hay espacio",
        ],
        answerIndex: 1,
        explanationEs: "auto-fit crea tantas columnas como quepan y minmax permite crecer hasta 1fr.",
        explanationEn: "auto-fit creates as many columns as fit and minmax allows them to grow up to 1fr.",
      },
      {
        questionEs: "Cual es la diferencia entre estado local y global en React?",
        questionEn: "What's the difference between local and global state in React?",
        options: [
          "Ninguna, ambos viven en useState",
          "El local pertenece al componente y el global se comparte via context/store",
          "El global solo se puede mutar con Redux",
        ],
        answerIndex: 1,
        explanationEs: "El estado local vive en un componente; el global se comparte entre varios.",
        explanationEn: "Local state lives inside a component; global state is shared across components.",
      },
      {
        questionEs: "Que efecto tiene usar useEffect con un arreglo de dependencias vacio?",
        questionEn: "What happens when useEffect has an empty dependency array?",
        options: [
          "Se ejecuta en cada render",
          "Se ejecuta una sola vez al montar y limpia al desmontar",
          "Se ejecuta antes del primer render",
        ],
        answerIndex: 1,
        explanationEs: "Con [] el efecto corre una vez al montar y puede limpiar al desmontar.",
        explanationEn: "With [] the effect runs once on mount and can clean up on unmount.",
      },
      {
        questionEs: "Que hace box-sizing: border-box?",
        questionEn: "What does box-sizing: border-box do?",
        options: [
          "Suma padding y borde al tamano declarado",
          "Incluye padding y borde dentro del ancho/alto declarado",
          "Solo afecta a elementos inline",
        ],
        answerIndex: 1,
        explanationEs: "border-box incluye padding y borde dentro del tamano declarado, evitando que crezca.",
        explanationEn: "border-box includes padding and border within the declared size, avoiding growth.",
      },
    ],
  },
  {
    slug: "css-layout",
    title: "Layout con CSS",
    description: "Flexbox, grid y media queries para diseno responsive.",
    difficulty: Difficulty.easy,
    tags: ["frontend", "css", "layout"],
    items: [
      {
        questionEs: "Como conviertes un contenedor en flex?",
        questionEn: "How do you turn a container into a flex container?",
        options: ["display: flex", "position: flex", "flex: container"],
        answerIndex: 0,
        explanationEs: "display: flex activa el modelo flexbox en el contenedor.",
        explanationEn: "display: flex enables the flexbox layout for the container.",
      },
      {
        questionEs: "En un flex row, que controla justify-content?",
        questionEn: "In a flex row, what does justify-content control?",
        options: [
          "La alineacion en el eje transversal",
          "La alineacion en el eje principal",
          "El tamano de las columnas",
        ],
        answerIndex: 1,
        explanationEs: "justify-content alinea los elementos en el eje principal.",
        explanationEn: "justify-content aligns items along the main axis.",
      },
      {
        questionEs: "Que describe mejor a position: sticky?",
        questionEn: "Which best describes position: sticky?",
        options: [
          "Siempre se fija al viewport como fixed",
          "Se comporta como relative hasta alcanzar un offset y luego se fija",
          "Se ubica fuera del flujo y no ocupa espacio",
        ],
        answerIndex: 1,
        explanationEs: "sticky se comporta como relative y se fija al alcanzar el offset definido.",
        explanationEn: "sticky behaves like relative and sticks once it reaches the defined offset.",
      },
      {
        questionEs: "Para que sirve la propiedad gap en flex o grid?",
        questionEn: "What is the gap property used for in flex or grid?",
        options: [
          "Agrega espacio entre elementos sin afectar los margenes externos",
          "Aumenta el padding del contenedor",
          "Solo funciona en tablas",
        ],
        answerIndex: 0,
        explanationEs: "gap crea separacion entre filas y columnas sin margenes extra.",
        explanationEn: "gap creates spacing between rows and columns without extra margins.",
      },
      {
        questionEs: "Que media query aplica estilos en pantallas de 768px o menos?",
        questionEn: "Which media query targets screens 768px wide or less?",
        options: [
          "@media (min-width: 768px)",
          "@media (max-width: 768px)",
          "@media (width >= 768px)",
        ],
        answerIndex: 1,
        explanationEs: "max-width aplica reglas cuando el ancho es menor o igual al limite.",
        explanationEn: "max-width applies rules when the viewport is at or below the limit.",
      },
    ],
  },
  {
    slug: "javascript-core",
    title: "JavaScript Esencial",
    description: "Tipos, funciones y asincronia basica.",
    difficulty: Difficulty.easy,
    tags: ["javascript", "fundamentals"],
    items: [
      {
        questionEs: "Que diferencia a === de ==?",
        questionEn: "What is the difference between === and ==?",
        options: [
          "=== compara tipo y valor sin coercion",
          "== es mas estricto",
          "No hay diferencia",
        ],
        answerIndex: 0,
        explanationEs: "=== compara sin conversion implicita de tipos.",
        explanationEn: "=== compares without implicit type coercion.",
      },
      {
        questionEs: "Con const en objetos, que es cierto?",
        questionEn: "With const on objects, what is true?",
        options: [
          "No se puede modificar ninguna propiedad",
          "Se puede mutar el contenido pero no reasignar la referencia",
          "const convierte el objeto en inmutable",
        ],
        answerIndex: 1,
        explanationEs: "const evita reasignar la referencia, pero permite mutar propiedades.",
        explanationEn: "const prevents reassignment but still allows property mutations.",
      },
      {
        questionEs: "Que retorna Array.prototype.map?",
        questionEn: "What does Array.prototype.map return?",
        options: [
          "El mismo array modificado",
          "Un nuevo array con la misma longitud",
          "Un numero con la suma",
        ],
        answerIndex: 1,
        explanationEs: "map transforma cada elemento y devuelve un nuevo array.",
        explanationEn: "map transforms each element and returns a new array.",
      },
      {
        questionEs: "Como se comporta Promise.all?",
        questionEn: "How does Promise.all behave?",
        options: [
          "Resuelve cuando todas resuelven y rechaza si alguna falla",
          "Resuelve con la primera promesa completada",
          "Ignora errores y siempre resuelve",
        ],
        answerIndex: 0,
        explanationEs: "Promise.all falla si cualquier promesa falla y resuelve cuando todas cumplen.",
        explanationEn: "Promise.all rejects if any promise fails and resolves when all succeed.",
      },
      {
        questionEs: "Que alcance tiene let?",
        questionEn: "What scope does let have?",
        options: ["Global siempre", "Funcion unicamente", "Bloque"],
        answerIndex: 2,
        explanationEs: "let tiene alcance de bloque.",
        explanationEn: "let has block scope.",
      },
    ],
  },
  {
    slug: "typescript-typing",
    title: "TypeScript Tipado",
    description: "Utilidades y patrones de tipado en TS.",
    difficulty: Difficulty.medium,
    tags: ["typescript", "frontend"],
    items: [
      {
        questionEs: "Que diferencia hay entre unknown y any?",
        questionEn: "What's the difference between unknown and any?",
        options: [
          "unknown obliga a validar el tipo antes de usarlo",
          "any es mas seguro",
          "unknown se puede usar sin checks",
        ],
        answerIndex: 0,
        explanationEs: "unknown requiere chequeos de tipo antes de acceder a sus propiedades.",
        explanationEn: "unknown requires type checks before accessing properties.",
      },
      {
        questionEs: "Para que sirve as const?",
        questionEn: "What is as const used for?",
        options: [
          "Convierte un objeto en mutable",
          "Reduce a literales y marca propiedades como readonly",
          "Elimina el tipo de la variable",
        ],
        answerIndex: 1,
        explanationEs: "as const hace inferencia literal y vuelve readonly las propiedades.",
        explanationEn: "as const enables literal inference and marks properties as readonly.",
      },
      {
        questionEs: "Que hace Partial<T>?",
        questionEn: "What does Partial<T> do?",
        options: [
          "Hace todas las propiedades opcionales",
          "Elimina propiedades undefined",
          "Convierte a readonly",
        ],
        answerIndex: 0,
        explanationEs: "Partial convierte todas las propiedades en opcionales.",
        explanationEn: "Partial makes all properties optional.",
      },
      {
        questionEs: "Que representa Record<K, T>?",
        questionEn: "What does Record<K, T> represent?",
        options: [
          "Un array de T",
          "Un objeto con claves K y valores T",
          "Una tupla de K y T",
        ],
        answerIndex: 1,
        explanationEs: "Record define un objeto indexado por K con valores T.",
        explanationEn: "Record defines an object indexed by K with values of type T.",
      },
      {
        questionEs: "Que caracteristica es propia de interface frente a type?",
        questionEn: "Which feature is specific to interface compared to type?",
        options: [
          "Puede fusionarse mediante declaracion multiple",
          "Puede representar uniones",
          "Puede tipar funciones",
        ],
        answerIndex: 0,
        explanationEs: "interface admite declaracion multiple y se fusiona automaticamente.",
        explanationEn: "interface supports declaration merging automatically.",
      },
    ],
  },
  {
    slug: "react-patterns",
    title: "Patrones en React",
    description: "Buenas practicas para estado y rendimiento.",
    difficulty: Difficulty.medium,
    tags: ["react", "frontend"],
    items: [
      {
        questionEs: "Por que es importante la prop key en listas?",
        questionEn: "Why is the key prop important in lists?",
        options: [
          "Para ordenar visualmente los elementos",
          "Para ayudar a React a reconciliar y reutilizar nodos",
          "Para mejorar el SEO",
        ],
        answerIndex: 1,
        explanationEs: "keys estables ayudan a React a identificar elementos entre renders.",
        explanationEn: "Stable keys help React identify items across renders.",
      },
      {
        questionEs: "Que es un componente controlado?",
        questionEn: "What is a controlled component?",
        options: [
          "Su valor vive en el estado y se actualiza con onChange",
          "No usa estado nunca",
          "Solo existe en formularios HTML",
        ],
        answerIndex: 0,
        explanationEs: "En un controlado el valor se deriva del estado del componente.",
        explanationEn: "A controlled component gets its value from component state.",
      },
      {
        questionEs: "Para que usar useRef en lugar de useState?",
        questionEn: "Why use useRef instead of useState?",
        options: [
          "Para guardar un valor mutable sin re-render",
          "Para disparar render extra",
          "Para hacer fetch de datos",
        ],
        answerIndex: 0,
        explanationEs: "useRef guarda valores mutables sin disparar renders.",
        explanationEn: "useRef stores mutable values without triggering renders.",
      },
      {
        questionEs: "Cuando tiene sentido usar React.memo?",
        questionEn: "When does it make sense to use React.memo?",
        options: [
          "En componentes puros con props estables",
          "En cualquier componente sin excepcion",
          "Para manejar estado global",
        ],
        answerIndex: 0,
        explanationEs: "React.memo evita renders si las props no cambian.",
        explanationEn: "React.memo prevents renders when props are unchanged.",
      },
      {
        questionEs: "Que significa lifting state up?",
        questionEn: "What does lifting state up mean?",
        options: [
          "Mover el estado a un padre comun para compartirlo",
          "Copiar estado en varios componentes",
          "Guardar estado en localStorage",
        ],
        answerIndex: 0,
        explanationEs: "Se eleva el estado a un ancestro para compartirlo entre hijos.",
        explanationEn: "You move state to a common ancestor to share it between children.",
      },
    ],
  },
  {
    slug: "api-design",
    title: "Diseno de APIs",
    description: "Escenarios sobre seguridad y contratos en APIs modernas.",
    difficulty: Difficulty.medium,
    tags: ["backend", "api", "security"],
    items: [
      {
        questionEs: "Que ventaja aporta GraphQL frente a REST en clientes moviles?",
        questionEn: "Which benefit does GraphQL bring to mobile clients versus REST?",
        options: [
          "Menos roundtrips al servidor con queries a medida",
          "Reemplaza OAuth2 en autenticacion",
          "Evita el versionado de APIs",
        ],
        answerIndex: 0,
        explanationEs: "GraphQL permite pedir exactamente los campos necesarios, reduciendo payload.",
        explanationEn: "GraphQL lets clients ask for exact fields, reducing payload size.",
      },
      {
        questionEs: "Como proteges endpoints criticos en REST?",
        questionEn: "How do you protect critical REST endpoints?",
        options: [
          "Solo con CORS",
          "Aplicando auth, rate limiting y validacion de entradas",
          "Con logs en consola",
        ],
        answerIndex: 1,
        explanationEs: "Seguridad basica implica autenticacion, rate limiting y sanitizar inputs.",
        explanationEn: "Baseline security requires auth, rate limiting, and input validation.",
      },
      {
        questionEs: "Que HTTP status usarias para un payload invalido?",
        questionEn: "Which HTTP status fits an invalid payload?",
        options: ["200 OK", "400 Bad Request", "302 Found"],
        answerIndex: 1,
        explanationEs: "400 indica que el cliente envio datos incorrectos o incompletos.",
        explanationEn: "400 signals the client sent malformed or incomplete data.",
      },
      {
        questionEs: "Que metodo HTTP NO es idempotente por definicion?",
        questionEn: "Which HTTP method is NOT idempotent by definition?",
        options: ["GET", "POST", "PUT"],
        answerIndex: 1,
        explanationEs: "POST suele crear recursos y repetirlo cambia el estado del servidor.",
        explanationEn: "POST usually creates resources, so repeating it changes server state.",
      },
      {
        questionEs: "Que deberia devolver un 201 Created?",
        questionEn: "What should a 201 Created response include?",
        options: [
          "El recurso creado y header Location",
          "Un 200 OK con texto plano",
          "Un redirect 302",
        ],
        answerIndex: 0,
        explanationEs: "201 indica creacion y suele incluir Location al recurso nuevo.",
        explanationEn: "201 indicates creation and typically includes a Location header.",
      },
    ],
  },
  {
    slug: "auth-security",
    title: "Auth y Seguridad",
    description: "Buenas practicas para proteger sesiones y credenciales.",
    difficulty: Difficulty.hard,
    tags: ["backend", "security", "auth"],
    items: [
      {
        questionEs: "Que atributo impide que JavaScript lea una cookie?",
        questionEn: "Which attribute prevents JavaScript from reading a cookie?",
        options: ["HttpOnly", "Secure", "SameSite"],
        answerIndex: 0,
        explanationEs: "HttpOnly bloquea el acceso desde JS y reduce riesgo de XSS.",
        explanationEn: "HttpOnly blocks JS access and reduces XSS risk.",
      },
      {
        questionEs: "Como mitigamos CSRF en formularios web?",
        questionEn: "How do we mitigate CSRF in web forms?",
        options: [
          "Token CSRF y cookies SameSite",
          "Solo CORS",
          "Solo HTTPS",
        ],
        answerIndex: 0,
        explanationEs: "Tokens CSRF y SameSite ayudan a validar el origen de la peticion.",
        explanationEn: "CSRF tokens and SameSite cookies help validate request origin.",
      },
      {
        questionEs: "Como deben almacenarse las contrasenas?",
        questionEn: "How should passwords be stored?",
        options: [
          "Hash con bcrypt/argon2 y salt",
          "Cifrado reversible",
          "Texto plano",
        ],
        answerIndex: 0,
        explanationEs: "Se deben almacenar como hashes seguros con salt.",
        explanationEn: "They should be stored as secure salted hashes.",
      },
      {
        questionEs: "Que objetivo principal tiene el rate limiting en login?",
        questionEn: "What is the main goal of rate limiting on login?",
        options: [
          "Evitar fuerza bruta y abuso",
          "Mejorar SEO",
          "Reducir latencia",
        ],
        answerIndex: 0,
        explanationEs: "Limita intentos para frenar ataques de fuerza bruta.",
        explanationEn: "It limits attempts to slow down brute force attacks.",
      },
      {
        questionEs: "Para que sirve un refresh token?",
        questionEn: "What is a refresh token used for?",
        options: [
          "Obtener un nuevo access token sin re-autenticar",
          "Reemplazar HTTPS",
          "Guardar preferencias de usuario",
        ],
        answerIndex: 0,
        explanationEs: "Permite renovar el access token sin pedir credenciales de nuevo.",
        explanationEn: "It renews access tokens without asking for credentials again.",
      },
    ],
  },
  {
    slug: "database-basics",
    title: "Fundamentos de Bases de Datos",
    description: "Consultas SQL y consistencia de datos.",
    difficulty: Difficulty.medium,
    tags: ["database", "sql"],
    items: [
      {
        questionEs: "Que hace un indice en una columna?",
        questionEn: "What does an index on a column do?",
        options: [
          "Garantiza unicidad siempre",
          "Acelera busquedas a costa de escrituras",
          "Impide borrados",
        ],
        answerIndex: 1,
        explanationEs: "Los indices aceleran lecturas, pero agregan costo en escrituras.",
        explanationEn: "Indexes speed up reads while adding overhead to writes.",
      },
      {
        questionEs: "Que significa ACID?",
        questionEn: "What does ACID stand for?",
        options: [
          "Atomicidad, Consistencia, Aislamiento, Durabilidad",
          "Alta Concurrencia e Integridad de Datos",
          "Async, Cache, Isolation, Data",
        ],
        answerIndex: 0,
        explanationEs: "ACID resume garantias de transacciones fiables.",
        explanationEn: "ACID summarizes reliable transaction guarantees.",
      },
      {
        questionEs: "Que devuelve un LEFT JOIN?",
        questionEn: "What does a LEFT JOIN return?",
        options: [
          "Todas las filas de la tabla izquierda aunque no haya match",
          "Solo las coincidencias entre tablas",
          "Solo filas de la tabla derecha",
        ],
        answerIndex: 0,
        explanationEs: "LEFT JOIN conserva todas las filas de la izquierda y llena nulls si no hay match.",
        explanationEn: "LEFT JOIN keeps all left rows and fills nulls when no match exists.",
      },
      {
        questionEs: "Cuando se usa HAVING en SQL?",
        questionEn: "When do you use HAVING in SQL?",
        options: [
          "Para filtrar despues de agregaciones",
          "Para ordenar resultados",
          "Para crear indices",
        ],
        answerIndex: 0,
        explanationEs: "HAVING filtra resultados agregados, mientras WHERE filtra antes de agrupar.",
        explanationEn: "HAVING filters aggregated results, while WHERE filters before grouping.",
      },
      {
        questionEs: "Que es un indice compuesto?",
        questionEn: "What is a composite index?",
        options: [
          "Indice sobre multiples columnas",
          "Indice que no se actualiza",
          "Indice unico sobre una sola columna",
        ],
        answerIndex: 0,
        explanationEs: "Un indice compuesto combina varias columnas para optimizar consultas conjuntas.",
        explanationEn: "A composite index combines multiple columns to optimize joint queries.",
      },
    ],
  },
  {
    slug: "devops-delivery",
    title: "DevOps y Delivery",
    description: "Automatizacion, despliegue y observabilidad basica.",
    difficulty: Difficulty.medium,
    tags: ["devops", "ci-cd", "infra"],
    items: [
      {
        questionEs: "Que objetivo tiene un pipeline CI/CD?",
        questionEn: "What is the goal of a CI/CD pipeline?",
        options: [
          "Automatizar build, tests y despliegues",
          "Reemplazar Git",
          "Evitar usar contenedores",
        ],
        answerIndex: 0,
        explanationEs: "CI/CD automatiza integracion, pruebas y despliegue para reducir errores.",
        explanationEn: "CI/CD automates integration, testing, and deployment to reduce errors.",
      },
      {
        questionEs: "Cual es la diferencia entre imagen y contenedor en Docker?",
        questionEn: "What is the difference between a Docker image and a container?",
        options: [
          "La imagen es un template; el contenedor es la instancia en ejecucion",
          "El contenedor es un backup de la imagen",
          "Son exactamente lo mismo",
        ],
        answerIndex: 0,
        explanationEs: "La imagen define el entorno; el contenedor es esa imagen en ejecucion.",
        explanationEn: "The image defines the environment; the container is the running instance.",
      },
      {
        questionEs: "Para que sirven los health checks?",
        questionEn: "What are health checks used for?",
        options: [
          "Detectar servicios no saludables para reiniciar o sacar de balanceo",
          "Aumentar el ancho de banda",
          "Compilar imagenes mas rapido",
        ],
        answerIndex: 0,
        explanationEs: "Los health checks validan que la app responde y ayudan a orquestacion.",
        explanationEn: "Health checks validate app responsiveness and help orchestration.",
      },
      {
        questionEs: "Que ventaja ofrece un despliegue blue/green?",
        questionEn: "What advantage does a blue/green deployment offer?",
        options: [
          "Cambia trafico entre dos entornos para reducir downtime",
          "Obliga a reiniciar la base de datos",
          "Elimina la necesidad de pruebas",
        ],
        answerIndex: 0,
        explanationEs: "Blue/green permite cambiar trafico y volver atras rapidamente.",
        explanationEn: "Blue/green enables traffic switching and fast rollbacks.",
      },
      {
        questionEs: "Por que usar variables de entorno para configuracion?",
        questionEn: "Why use environment variables for configuration?",
        options: [
          "Separan configuracion del codigo por entorno",
          "Hacen el codigo mas lento",
          "Impiden usar contenedores",
        ],
        answerIndex: 0,
        explanationEs: "Permiten cambiar configuracion sin modificar el codigo.",
        explanationEn: "They allow config changes without modifying code.",
      },
    ],
  },
  {
    slug: "testing-quality",
    title: "Testing y Calidad",
    description: "Estrategias para asegurar calidad de software.",
    difficulty: Difficulty.hard,
    tags: ["testing", "quality"],
    items: [
      {
        questionEs: "Que caracteriza a un test unitario?",
        questionEn: "What characterizes a unit test?",
        options: [
          "Aisla una funcion o modulo sin dependencias externas",
          "Requiere base de datos real",
          "Siempre usa navegador real",
        ],
        answerIndex: 0,
        explanationEs: "Un test unitario prueba una pieza pequena de codigo en aislamiento.",
        explanationEn: "A unit test checks a small piece of code in isolation.",
      },
      {
        questionEs: "Que es un mock?",
        questionEn: "What is a mock?",
        options: [
          "Una simulacion que valida interacciones esperadas",
          "Un dato fijo sin comportamiento",
          "Un test end-to-end",
        ],
        answerIndex: 0,
        explanationEs: "Los mocks simulan dependencias y permiten verificar llamadas.",
        explanationEn: "Mocks simulate dependencies and let you verify interactions.",
      },
      {
        questionEs: "Que indica la piramide de pruebas?",
        questionEn: "What does the test pyramid indicate?",
        options: [
          "Mas tests unitarios, menos integracion y E2E",
          "Mas E2E que unitarios",
          "Solo tests manuales",
        ],
        answerIndex: 0,
        explanationEs: "La piramide recomienda muchas unitarias y pocas E2E por costo.",
        explanationEn: "The pyramid recommends many unit tests and fewer E2E tests.",
      },
      {
        questionEs: "Que causa tipica hace un test flaky?",
        questionEn: "What typically causes a flaky test?",
        options: [
          "Dependencias de tiempo o asincronia no controlada",
          "Demasiados asserts",
          "Uso de TypeScript",
        ],
        answerIndex: 0,
        explanationEs: "Los tests que dependen del tiempo o la red tienden a fallar intermitentemente.",
        explanationEn: "Time or network dependent tests tend to fail intermittently.",
      },
      {
        questionEs: "Cual es el orden recomendado en un test?",
        questionEn: "What is the recommended order in a test?",
        options: [
          "Arrange, Act, Assert",
          "Assert, Act, Arrange",
          "Act, Arrange, Assert",
        ],
        answerIndex: 0,
        explanationEs: "AAA organiza la preparacion, ejecucion y verificacion.",
        explanationEn: "AAA organizes setup, execution, and verification.",
      },
    ],
  },
  {
    slug: "git-workflow",
    title: "Git y Colaboracion",
    description: "Comandos esenciales para trabajo en equipo.",
    difficulty: Difficulty.easy,
    tags: ["git", "collaboration"],
    items: [
      {
        questionEs: "Que hace git rebase?",
        questionEn: "What does git rebase do?",
        options: [
          "Reescribe historial aplicando commits sobre otra rama",
          "Crea un merge commit automaticamente",
          "Borra la rama remota",
        ],
        answerIndex: 0,
        explanationEs: "rebase reaplica commits sobre otra base y reescribe el historial.",
        explanationEn: "rebase reapplies commits onto another base and rewrites history.",
      },
      {
        questionEs: "Que comando deshace un commit creando uno nuevo?",
        questionEn: "Which command undoes a commit by creating a new one?",
        options: ["git revert", "git reset --hard", "git checkout ."],
        answerIndex: 0,
        explanationEs: "git revert genera un commit inverso y mantiene el historial.",
        explanationEn: "git revert creates an inverse commit and preserves history.",
      },
      {
        questionEs: "Para que sirve .gitignore?",
        questionEn: "What is .gitignore used for?",
        options: [
          "Evitar que ciertos archivos se rastreen en Git",
          "Eliminar archivos del repositorio remoto",
          "Renombrar ramas automaticamente",
        ],
        answerIndex: 0,
        explanationEs: ".gitignore evita agregar archivos que no deben versionarse.",
        explanationEn: ".gitignore prevents tracking files that shouldn't be versioned.",
      },
      {
        questionEs: "Que significa hacer squash de commits?",
        questionEn: "What does squashing commits mean?",
        options: [
          "Combinar varios commits en uno solo",
          "Borrar el historial por completo",
          "Crear tags automaticamente",
        ],
        answerIndex: 0,
        explanationEs: "Squash agrupa varios commits en uno para un historial mas limpio.",
        explanationEn: "Squash combines multiple commits into one for a cleaner history.",
      },
      {
        questionEs: "Que hace git fetch?",
        questionEn: "What does git fetch do?",
        options: [
          "Descarga cambios remotos sin mezclarlos en tu rama",
          "Hace merge automatico de la rama remota",
          "Elimina ramas locales",
        ],
        answerIndex: 0,
        explanationEs: "git fetch actualiza referencias remotas sin modificar tu working tree.",
        explanationEn: "git fetch updates remote references without changing your working tree.",
      },
    ],
  },
];
