name: " Reporte de bug"
description: "Informa un error reproducible en el diccionario"
title: "[Bug]: "
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tu reporte. Proporciona toda la informaci贸n posible para acelerar la correcci贸n.
  - type: textarea
    id: contexto
    attributes:
      label: Contexto
      description: 驴D贸nde apareci贸 el bug? Describe flujo, URL o m贸dulo afectado.
      placeholder: "Vista de t茅rminos, endpoint /api/terms, etc."
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      description: Lista numerada con los pasos exactos.
      placeholder: |
        1. Ir a /terms
        2. Buscar "flex"
        3. Hacer clic en...
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento esperado
      placeholder: "El usuario deber铆a ver..."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
      description: Incluye logs, errores de consola o capturas si aplica.
      placeholder: "Error 500, screenshot..."
    validations:
      required: true
  - type: dropdown
    id: severidad
    attributes:
      label: Severidad
      options:
        - Baja
        - Media
        - Alta
    validations:
      required: true
  - type: input
    id: entorno
    attributes:
      label: Entorno
      placeholder: "Prod, Staging, Local"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versi贸n o commit
      placeholder: "v1.2.3 / abc1234"
